name: PR merge check

on:
  push:
    branches:
      - main
      - develop
      - stage
jobs:
  check_merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get commit log
        run: git log -1

      - name: Check if merge commit
        run: |
          if git log -1 --merges --pretty=format:'%h' | grep -q .; then
            echo "Pull request was merged !!!!."
          else
            echo "Pull request was not merged."
          fi
