name: My Workflow
on: 
  push:
    branches:
      - main
      - develop
      - stage

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: List pull requests
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            console.log(pulls.map(pull => pull.number).join(', '));
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Check branches containing features
        run: |
          git fetch --all
          for pull_url in $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=open" \
              | grep -oP '(?<="url": ")[^"]*'); do
            feature_branch=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              $pull_url \
              | grep -oP '(?<="ref": ")[^"]*' \
              | sed "s/.*:\\(.*\\)/\\1/")
            git branch --contains $feature_branch
          done
