name: My Workflow
on: 
  push:
    branches:
      - main
      - develop
      - stage

env:
  FILTERED_BRANCHES: ""

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Labeling on filtered branches
        run: |
          git fetch
          FILTERED_BRANCHES=$(git branch --remotes --list | grep -o "feature/.*")
          CURRENT_BRANCH=$(git branch --show-current)
          LABEL=""

          if [[ $CURRENT_BRANCH == 'main' ]]; then
            LABEL='production'
          elif [[ $CURRENT_BRANCH == 'develop' ]]; then
            LABEL='develop'
          elif [[ $CURRENT_BRANCH == 'stage' ]]; then
            LABEL='stage'
          fi

          for branch in $FILTERED_BRANCHES; do
            echo "1---- $CURRENT_BRANCH"
            echo "2---- $FILTERED_BRANCHES"
            echo "3---- $LABEL"
            echo "4---- $branch"
            GET_MERGED = $(git branch --contains $branch)
            echo "MGMG: &GET_MERGED"
            if git branch --contains $branch; then
              echo '5 ---------------'
              gh pr list --state open | grep $branch | awk '{print $1}'
              PR_NUMBER=$(gh pr list --state open | grep -m1 "$branch" | awk '{print $1}')
              echo "PR NUM : $PR_NUMBER"
              curl --request POST \
                --url https://api.github.com/repos/garyjeong/gary-backend-nestjs/issues/$PR_NUMBER/labels \
                --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                --header 'content-type: application/json' \
                --data '{"labels": ["'"$LABEL"'"]}'
            fi
          done
        


        
