name: My Workflow
on: 
  push:
    branches:
      - main
      - develop
      - stage

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filtering Feature Branches
        run: |
          export FILTERED_BRANCHES=$(git branch --remotes --list | grep -o "feature/.*")
          
          echo "FIL BRANCH: ${FILTERED_BRANCHES}"

      - name: Labeling on filtered branches
        run: |
          FILTERED_BRANCHES=$(git branch --remotes --list | grep -o "feature/.*")
          CURRENT_BRANCH=$(git branch --show-current)
          LABEL=""

          if [[ $CURRENT_BRANCH == 'main' ]]; then
            LABEL='production'
          elif [[ $CURRENT_BRANCH == 'develop' ]]; then
            LABEL='develop'
          elif [[ $CURRENT_BRANCH == 'stage' ]]; then
            LABEL='stage'
          fi


          echo "CUR BRANCH: ${CURRENT_BRANCH}"
          echo "FIL BRANCH: ${FILTERED_BRANCHES}"
          echo "LABEL: ${LABEL}"
          
          for branch in $FILTERED_BRANCHES; do
            if git branch --contains $branch; then
              PR_NUMBER=$(gh pr list --state open | grep "$branch" | awk '{print $1}')
              echo "ADD LABEL : $branch"
              echo "PR NUM" : $PR_NUMBER"
              curl --request POST \
                --url https://api.github.com/repos/garyjeong/gary-backend-nestjs/issues/$PR_NUMBER/labels \
                --header 'authorization: Bearer ${{ secrets.ACTION_TOKEN }}' \
                --header 'content-type: application/json' \
                --data "{\"labels\": [\"$LABEL\"]}"
            fi
          done
        
