name: My Workflow
on:
  push:
    branches:
      - front
      - qa

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Labeling on filtered branches
        run: |
          git fetch
          FILTERED_BRANCHES=$(git branch --remotes --list | grep "feature/.*")
          CURRENT_BRANCH=$(git branch --show-current)
          LABEL=""

          if [[ $CURRENT_BRANCH == 'front' ]]; then
            LABEL='dev merged'
          elif [[ $CURRENT_BRANCH == 'qa' ]]; then
            LABEL='front merged'
          fi

          for branch in $FILTERED_BRANCHES; do
            if git branch --contains $branch | grep "$CURRENT_BRANCH"; then
              PR_NUMBER=$(gh pr list --state open | grep -m1 feature/${branch##*/} | awk '{print $1}')

              curl --request POST \
                --url https://api.github.com/repos/Rencar-dev/overseas-api/issues/$PR_NUMBER/labels \
                --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}' \
                --header 'content-type: application/json' \
                --data '{"labels": ["'"$LABEL"'"]}'
            fi
          done
