name: My Workflow
on: 
  push:
    branches:
      - main
      - develop
      - stage

env:
  FILTERED_BRANCHES: ""

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filtering Feature Branches
        run: |
          export FILTERED_BRANCHES=$(git branch --remotes --list | grep -o "feature/*")

      - name: Labeling on filtered branches
        run: |
          CURRENT_BRANCH=$(git branch --show-current)
          LABEL=""

          if [[ $CURRENT_BRANCH == 'main' ]]; then
            LABEL='production'
          elif [[ $CURRENT_BRANCH == 'develop' ]]; then
            LABEL='develop'
          elif [[ $CURRENT_BRANCH == 'stage' ]]; then
            LABEL='stage'
          fi

          for branch in $FILTERED_BRANCHES; do
            if git branch --contains $CURRENT_BRANCH $branch >/dev/null 2>&1; then
              PR_NUMBER=$(gh pr list --state open | grep "$branch" | awk '{print $1}')
              echo "Adding label to $branch"
              curl --request POST \
                --url https://api.github.com/repos/{owner}/{repo}/issues/$PR_NUMBER/labels \
                --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                --header 'content-type: application/json' \
                --data "{\"labels\": [\"$LABEL\"]}"
            fi
          done
        
