name: My Workflow
on: 
  push:
    branches:
      - main
      - develop
      - stage

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filtering Feature Branches
        run: |
          export FILTERED_BRANCHES=$(git branch --remotes --list | grep -o "feature/*")

      - name: Do something on filtered branches
        run: |
          CURRENT_BRANCH=$(git branch --show-current)

          for branch in $FILTERED_BRANCHES; do
            if git branch --contains $CURRENT_BRANCH $branch >/dev/null 2>&1; then
              echo "Processing branch $branch that contains $CURRENT_BRANCH"
            else
              echo "Processing branch $branch that does not contain $CURRENT_BRANCH"
            fi
          done
