name: My Workflow
on: 
  push:
    branches:
      - main
      - develop
      - stage
      
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        uses: actions/checkout@v2
        with:
          branches: ${{ matrix.branches }}
