name: My Workflow
on: 
  push:
    branches:
      - main
      - develop
      - stage

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Labeling on filtered branches
        run: |
          git fetch
          FILTERED_BRANCHES=$(git branch --remotes --list | grep "feature/.*")
          CURRENT_BRANCH=$(git branch --show-current)
          LABEL=""

          if [[ $CURRENT_BRANCH == 'main' ]]; then
            LABEL='production'
          elif [[ $CURRENT_BRANCH == 'develop' ]]; then
            LABEL='develop'
          elif [[ $CURRENT_BRANCH == 'stage' ]]; then
            LABEL='stage'
          fi

          for branch in $FILTERED_BRANCHES; do
            if git branch --contains $branch | grep "$CURRENT_BRANCH"; then
              echo "$(gh pr list --state open | grep -m1 feature/${branch##*/})"
              PR_NUMBER=$(gh pr list --state open | grep -m1 feature/${branch##*/} | awk '{print $1}')
              echo "PR : $PR_NUMBER"
            fi
          done

          export FILTERED_BRANCHES=$FILTERED_BRANCHES
          export CURRENT_BRANCH=$CURRENT_BRANCH
      - name: test
        run: |
          echo "CUR BRANCH : $CURRENT_BRANCH"
          echo "LABEL : $LABEL"
          git fetch
          git checkout develop
          gh pr list --state open | grep -m1 feature/testttt | awk '{print $1}'


