name: My Workflow
on:
  push:
    branches:
      - stage

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: 
  pull-requests: write
jobs:
  list-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Labeling on filtered branches
        run: |
          git fetch
          FILTERED_BRANCHES=$(git branch --remotes --list | grep "feature/.*")
          CURRENT_BRANCH=$(git branch --show-current)
          LABEL=""

          if [[ $CURRENT_BRANCH == 'stage' ]]; then
            LABEL='stage'
          elif [[ $CURRENT_BRANCH == 'qa' ]]; then
            LABEL='front merged'
          fi

          for branch in $FILTERED_BRANCHES; do
            if git branch --contains $branch | grep "$CURRENT_BRANCH"; then
              PR_NUMBER=$(gh pr list --state open | grep -m1 feature/${branch##*/} | awk '{print $1}')
              echo https://api.github.com/repos/${{github.repository_owner}}/${{github.repository}}/issues/$PR_NUMBER/labels
              curl -X POST https://api.github.com/repos/${{github.repository_owner}}/${{github.repository}}/issues/$PR_NUMBER/labels -H "Authorization: Bearer ${{ env.GH_TOKEN }}" -d '{"labels": ["'"$LABEL"'"]}'
            fi
          done
