name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: smat91/gary-backend-nestjs
          stage: main
          yaml: |
            name: gary-backend-nestjs
            app: node@18
            options:
              env:
                - name: APP_ENV
                  value: develop
                - name: DB_HOST
                  value: svc.sel4.cloudtype.app
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: root
                - name: DB_PASSWORD
                  secret: mariadb-root-password
                - name: DB_NAME
                  value: root
                - name: DB_SYNC
                  value: "false"
              ports: "3000"
              build: npm run build
              start: npm run start:prod
              install: npm i
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
