name: Merge Workflow
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  add-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Get branch name
      run: |
        echo "Merged branch name: ${{ github.event.pull_request.head.ref }}"
    - name: Add custom label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: 'custom label'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}