name: 'Labeling to Pull Request'

on:
  pull_request:
    types: ['opened', 'reopened', 'closed']
    branches:
      - feature/*
  push:
    branches-ignore:
      - feature/*
      - hotfix/*
      - dependabot/*


jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Condition Stage
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event.ref == 'refs/heads/stage'
        with:
          github_token: ${{ github.token }}
          labels: stage
          repo: garyjeong/gary-backend-nestjs
          number: ${{ github.event.pull_request.number }}
      
      - name: Check Values for github
        run: |
          echo ${{ github.event_name }}
          echo $github.event_name
          echo ${{ github.event.action }}
          echo $github.event.action
          echo ${{ github.event.pull_request.merged }}
          echo $github.event.pull_request.merged